export const FORWARD_TO = 'FORWARD_TO'

export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const EXPAND_MENU = 'EXPAND_MENU'
export const SWITCH_EFFECT = 'SWITCH_EFFECT'
export const SET_SESSION = 'SET_SESSION'

// loading and working states
export const SET_WORKING = 'SET_WORKING'
export const SET_LOADING = 'SET_LOADING'

// dCloud Cumulus
export const SET_VERTICALS = 'SET_VERTICALS'

// Finesse
export const SET_USE_DEFAULT = 'SET_USE_DEFAULT'
export const SET_LAYOUT_XML = 'SET_LAYOUT_XML'
export const SET_FINESSE_OBJECTS = 'SET_FINESSE_OBJECTS'
export const ADD_GADGET = 'ADD_GADGET'

// export const SET_TEAMS = 'SET_TEAMS'
// export const SET_FINESSE_LOADING = 'SET_FINESSE_LOADING'
// export const SET_TEAM_PHONEBOOKS = 'SET_TEAM_PHONEBOOKS'
// export const SET_AVAILABLE_PHONEBOOKS = 'SET_AVAILABLE_PHONEBOOKS'
// export const SET_TEAM_WORKFLOWS = 'SET_TEAM_WORKFLOWS'
// export const SET_AVAILABLE_WORKFLOWS = 'SET_AVAILABLE_WORKFLOWS'
// export const SET_TEAM_NOT_READY_REASON_CODES = 'SET_TEAM_NOT_READY_REASON_CODES'
// export const SET_AVAILABLE_NOT_READY_REASON_CODES = 'SET_AVAILABLE_NOT_READY_REASON_CODES'
// export const SET_TEAM_LOGOUT_REASON_CODES = 'SET_TEAM_LOGOUT_REASON_CODES'
// export const SET_AVAILABLE_LOGOUT_REASON_CODES = 'SET_AVAILABLE_LOGOUT_REASON_CODES'
// export const SET_TEAM_WRAPUP_REASON_CODES = 'SET_TEAM_WRAPUP_REASON_CODES'
// export const SET_AVAILABLE_WRAPUP_REASON_CODES = 'SET_AVAILABLE_WRAPUP_REASON_CODES'

export const SET_JWT = 'SET_JWT'

export const SET_USER = 'SET_USER'
export const SET_USERS = 'SET_USERS'

// Inbound Voice
export const SET_DIDS = 'SET_DIDS'
export const SET_INBOUND_DEMOS = 'SET_INBOUND_DEMOS'
export const SET_INBOUND_DEFAULTS = 'SET_INBOUND_DEFAULTS'

// Outbound Voice
export const SET_OUTBOUND_DEMOS = 'SET_OUTBOUND_DEMOS'
export const SET_OUTBOUND_DEFAULTS = 'SET_OUTBOUND_DEFAULTS'

// Post-Call Survey
export const SET_PCS_DEMOS = 'SET_PCS_DEMOS'

// File uploader repository
export const SET_FILES = 'SET_FILES'
export const SET_PATH = 'SET_PATH'

// branding website demo
export const SET_BRANDING_TEMPLATES = 'SET_BRANDING_TEMPLATES'

// user-defined templates
export const SET_TEMPLATES = 'SET_TEMPLATES'

// CVP
export const SET_VXML_APPS = 'SET_VXML_APPS'
export const SET_MEDIA_FILES = 'SET_MEDIA_FILES'
export const SET_VXML_APP_LOG_HOSTS = 'SET_VXML_APP_LOG_HOSTS'
export const SET_VXML_APP_LOG_FOLDERS = 'SET_VXML_APP_LOG_FOLDERS'
export const SET_VXML_APP_LOG_FILES = 'SET_VXML_APP_LOG_FILES'
export const SET_VXML_APP_LOG_FILE_CONTENTS = 'SET_VXML_APP_LOG_FILE_CONTENTS'
export const ADD_VXML_MEDIA_ANCHOR = 'ADD_VXML_MEDIA_ANCHOR'

// Agents
export const SET_AGENTS = 'SET_AGENTS'
export const SET_AVAILABLE_AGENT_IDS = 'SET_AVAILABLE_AGENT_IDS'
export const SET_ECE_QUEUES = 'SET_ECE_QUEUES'
export const SET_EGAIN_QUEUES = 'SET_EGAIN_QUEUES'

// CCE
export const SET_CCE_OBJECTS = 'SET_CCE_OBJECTS'

// Permissions
export const SET_PERMISSONS = 'SET_PERMISSONS'

// Mobile Connect
export const SET_MOBILE_CONNECT_BRANDS = 'SET_MOBILE_CONNECT_BRANDS'
export const SET_MOBILE_CONNECT_LOCALIZATIONS = 'SET_MOBILE_CONNECT_LOCALIZATIONS'

// REM
export const SET_COBROWSE_URLS = 'SET_COBROWSE_URLS'

// Facebook
export const SET_FACEBOOK_PAGES = 'SET_FACEBOOK_PAGES'

// SMS
export const SET_SMS_DEMOS = 'SET_SMS_DEMOS'
export const SET_SMS_DEFAULTS = 'SET_SMS_DEFAULTS'

// Bots
export const SET_BOTS = 'SET_BOTS'

// Spark
export const SET_SPARK_DEMOS = 'SET_SPARK_DEMOS'
export const SET_SPARK_DEFAULTS = 'SET_SPARK_DEFAULTS'

// push notifications
export const SET_PUSH_NOTIFICATIONS = 'SET_PUSH_NOTIFICATIONS'

// CUCM
export const SET_CUCM_LINES = 'SET_CUCM_LINES'
export const SET_CUCM_PHONES = 'SET_CUCM_PHONES'

// Callgen
export const SET_CALLGEN_CONFIG = 'SET_CALLGEN_CONFIG'
export const SET_CALLGEN_TEMPLATES = 'SET_CALLGEN_TEMPLATES'

// Routing
export const SET_ROUTING = 'SET_ROUTING'

// defaults
export const SET_DEFAULTS = 'SET_DEFAULTS'
export const SET_DEMOS = 'SET_DEMOS'

// Whatsapp
export const SET_WHATSAPP_DEMOS = 'SET_WHATSAPP_DEMOS'
export const SET_WHATSAPP_DEFAULTS = 'SET_WHATSAPP_DEFAULTS'
